Repository pie-sfac/5-17-smokedDuck, pull requests merged in 2023-08, with the labels that each got.

#58 refactor: 카테고리 컴포넌트 분리 및 기능 추가
  src/components/Category/CategoryDelete.tsx
  src/components/Category/CategoryHeader.tsx
  src/components/Category/CategoryListContents.tsx
  src/components/Category/CategorySelector.tsx
  src/components/Category/CategoryTab.tsx
  src/components/Category/index.tsx
  src/components/media/MediaCategorySelector.tsx
  src/pages/MediaManagementPage.tsx
Labels: fix, style, refactor

#57 feat: 링크 생성, 조회 api 연동
  src/apis/Category.ts
  src/apis/Media.ts
  src/components/Link/LinkForm.tsx
  src/components/Link/LinkView.tsx
  src/components/Link/index.tsx
  src/components/media/MediaCard.tsx
  src/components/media/MediaListContainer.tsx
  src/hooks/useMedia.ts
  src/types/category.interface.ts
  src/types/media.interface.ts
  src/utils/validations/linkUtils.ts
Labels: feat

#63 feat: 링크 수정 기능 구현
  src/apis/Category.ts
  src/apis/Media.ts
  src/components/Link/LinkForm.tsx
  src/components/Link/index.tsx
  src/components/common/DeleteModal/index.tsx
  src/components/common/EditBox.tsx
  src/pages/MediaManagementPage.tsx
  src/types/media.interface.ts
Labels: feat

#65 feat: 카테고리 조회 api 연동
  src/apis/Category.ts
  src/components/Category/CategoryListContents.tsx
  src/components/Category/index.tsx
  src/components/media/MediaCategorySelector.tsx
  src/hooks/useCategory.tsx
  src/utils/constants/categoryList.ts
Labels: feat

#68 fix: 로그인 토큰 저장소 변경
  src/components/LoginForm.tsx
  src/components/common/DeleteModal/index.tsx
  src/components/common/Header.tsx
  src/hooks/useCategory.tsx
  src/hooks/useRecord.tsx
  src/store/index.tsx
Labels: fix

#69 feat: 기록 템플릿 생성 api 연동 (처치)
  src/apis/Template.ts
  src/apis/record.ts
  src/components/Question/QuestionContent.tsx
  src/components/Question/QuestionFooter.tsx
  src/components/Question/QuestionHeader.tsx
  src/components/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateFooter.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/TemplateSelections.tsx
  src/components/Template/TemplateSubHeader.tsx
  src/components/Template/index.tsx
  src/components/common/QuestionBox.tsx
  src/components/common/SelectionBox.tsx
  src/hooks/useRecord.tsx
  src/store/index.tsx
  src/types/question.interface.ts
  src/types/template.interface.ts
Labels: feat

#71 fix: 미디어 기능 수정
  src/components/Link/LinkForm.tsx
  src/components/Link/LinkView.tsx
  src/components/Link/index.tsx
  src/components/common/DeleteModal/index.tsx
  src/components/common/EditBox.tsx
  src/components/media/MediaCard.tsx
  src/components/media/MediaListContainer.tsx
Labels: fix

#73 feat: 카테고리 추가,삭제, 수정 api 연동
  src/apis/Category.ts
  src/components/Category/CategoryListContents.tsx
  src/components/Category/index.tsx
  src/components/media/MediaCategorySelector.tsx
Labels: feat

#80 feat: 미디어 리스트 관리를 위한 커스텀 훅 제작
  src/components/media/MediaListContainer.tsx
  src/hooks/useMediaCards.tsx
Labels: feat

#84 fix: header 하이라이트 기능 수정
  src/components/common/Header.tsx
  src/store/index.tsx
Labels: fix

#94 feat: 카테고리별 링크 카드 필터링
  src/components/media/MediaCategorySelector.tsx
  src/components/media/MediaListContainer.tsx
  src/components/media/index.tsx
  src/hooks/useMediaCards.tsx
Labels: feat

#102 feat: 카테고리명 중복 방지
  src/components/Category/CategoryListContents.tsx
Labels: feat

#106 style: 미디어 빈화면
  src/assets/EmptyMedia.svg
  src/components/media/MediaListContainer.tsx
Labels: style, refactor

#109 refactor: 템플릿 생성 시 미디어 추가 버튼 및 기능 제거
  src/components/Question/QuestionContent.tsx
  src/components/RecordDetailItem/RecordDetailItemContent.tsx
Labels: style, refactor

#113 feat: 미디어 카드 정렬
  src/components/media/MediaListContainer.tsx
Labels: feat

#119 fix: 템플릿 생성 관련 에러 수정
  src/components/Question/QuestionContent.tsx
  src/components/Question/QuestionFooter.tsx
  src/components/Question/QuestionHeader.tsx
  src/components/Question/QuestionOptionalContent.tsx
  src/components/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/index.tsx
  src/components/common/QuestionBox.tsx
Labels: fix, refactor

#124 feat: 템플릿 생성 validate 추가
  src/components/Question/QuestionOptionalContent.tsx
  src/components/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateFooter.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/index.tsx
  src/components/common/QuestionBox.tsx
Labels: feat

#125 style: 모달창과 카드 리스트 반응형 디자인 적용
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/UpdateTemplate/UpdateTemplateSelectedQuestionContainer.tsx
  src/components/media/MediaCategorySelector.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordContents.tsx
  src/components/record/index.tsx
Labels: style

#128 !hotfix: merge revert branch
  src/components/Question/QuestionHeader.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateSubHeader.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionBox.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionContent.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionFooter.tsx
  src/components/UpdateTemplate/UpdateQuestion/index.tsx
  src/components/UpdateTemplate/UpdateTemplateContent.tsx
  src/components/UpdateTemplate/UpdateTemplateQuestionSelections.tsx
  src/components/UpdateTemplate/UpdateTemplateSelectedQuestionContainer.tsx
  src/components/UpdateTemplate/UpdateTemplateSubHeader.tsx
  src/components/UpdateTemplate/UpdateTemplateTitle.tsx
  src/components/UpdateTemplate/index.tsx
  src/components/common/Modal.tsx
  src/components/common/QuestionBox.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordInfo.tsx
  src/components/record/RecordModalTitle.tsx
  src/components/record/index.tsx
  src/types/question.interface.ts
  src/types/recordDetail.interface.ts
Labels: hotfix

#129 fix: 조회 컴포넌트 리팩토링과 버그 해결
  src/components/UpdateTemplate/UpdateTemplateContent.tsx
  src/components/UpdateTemplate/UpdateTemplateSelectedQuestionContainer.tsx
Labels: fix, refactor

#133 refactor: 조회 컴포넌트 리팩토링
  src/components/record/RecordCard.tsx
  src/components/record/RecordContents.tsx
  src/components/record/RecordInfo.tsx
  src/components/record/RecordModalHeader.tsx
  src/components/record/index.tsx
Labels: refactor

#136 feat: 템플릿 편집 항목 삭제 / 순서 조정 및 버그 수정
  src/components/Category/CategoryListContents.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionBox.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionContent.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionFooter.tsx
  src/components/UpdateTemplate/UpdateQuestion/index.tsx
  src/components/UpdateTemplate/UpdateTemplateContent.tsx
  src/components/UpdateTemplate/UpdateTemplateFooter.tsx
  src/components/UpdateTemplate/UpdateTemplateQuestionSelections.tsx
  src/components/UpdateTemplate/UpdateTemplateSelectedQuestionContainer.tsx
  src/components/UpdateTemplate/index.tsx
  src/components/record/RecordContents.tsx
  src/hooks/useRecordDetail.tsx
  src/types/template.interface.ts
Labels: feat, fix

#138 refactor: 추가 컴포넌트 구조 리팩토링
  src/components/Template/Question/QuestionContent.tsx
  src/components/Template/Question/QuestionFooter.tsx
  src/components/Template/Question/QuestionHeader.tsx
  src/components/Template/Question/QuestionOptionalContent.tsx
  src/components/Template/Question/index.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionBox.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionFooter.tsx
  src/components/UpdateTemplate/UpdateTemplateContent.tsx
  src/components/UpdateTemplate/UpdateTemplateQuestionSelections.tsx
  src/components/UpdateTemplate/UpdateTemplateSelectedQuestionContainer.tsx
  src/components/UpdateTemplate/UpdateTemplateTitle.tsx
  src/components/UpdateTemplate/index.tsx
  src/components/common/DeleteModal.tsx
  src/components/record/RecordContents.tsx
  src/components/record/RecordInfo.tsx
  src/components/record/RecordListContainer.tsx
  src/components/record/RecordModalHeader.tsx
  src/components/record/RecordModalTitle.tsx
  src/components/record/RecordTypeSelector.tsx
  src/components/record/index.tsx
  src/hooks/useRecordDetail.tsx
  src/utils/constants/template.ts
  src/utils/recordData.ts
Labels: refactor

#139 refactor: 공통 type 분리 및 컨벤션 일괄 적용
  src/apis/Login.ts
  src/apis/Template.ts
  src/components/Category/CategoryListContents.tsx
  src/components/Category/index.tsx
  src/components/Link/LinkForm.tsx
  src/components/Template/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/UpdateTemplateContent.tsx
  src/components/UpdateTemplate/UpdateTemplateTitle.tsx
  src/components/UpdateTemplate/index.tsx
  src/components/common/DeleteModal.tsx
  src/components/common/Header.tsx
  src/components/media/MediaCategorySelector.tsx
  src/components/media/MediaListContainer.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordListContainer.tsx
  src/components/record/RecordModalHeader.tsx
  src/store/index.tsx
  src/types/category.interface.ts
  src/types/question.interface.ts
  src/types/template.interface.ts
  src/types/token.interface.ts
  src/utils/categoryData.ts
  src/utils/constants/header.ts
  src/utils/validations/index.ts
Labels: refactor

#143 docs: readme
  README.md
Labels: docs

#144 style: 기록관리 편집 유효성 검증 경고창 변경
  src/components/UpdateTemplate/UpdateTemplateContent.tsx
  src/components/UpdateTemplate/UpdateTemplateFooter.tsx
  src/components/UpdateTemplate/UpdateTemplateQuestionSelections.tsx
  src/components/UpdateTemplate/index.tsx
Labels: style

#146 fix: 새로고침시에 로딩이 오래 걸리는부분 수정
  src/utils/categoryData.ts
  src/utils/mediaListData.ts
  src/utils/recordData.ts
Labels: fix

#147 style: 전반적인 스타일링 수정
  src/assets/Textline.svg
  src/components/Category/CategoryListContents.tsx
  src/components/Link/LinkForm.tsx
  src/components/Login/LoginForm.tsx
  src/components/Template/Question/QuestionContent.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/TemplateSubHeader.tsx
  src/components/Template/TemplateTitle.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionBox.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionContent.tsx
  src/components/UpdateTemplate/UpdateTemplateSelectedQuestionContainer.tsx
  src/components/UpdateTemplate/UpdateTemplateSubHeader.tsx
  src/components/UpdateTemplate/UpdateTemplateTitle.tsx
  src/components/common/EditBox.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/common/QuestionBox.tsx
  src/components/media/MediaCard.tsx
  src/components/media/MediaCategorySelector.tsx
  src/components/media/MediaContent.tsx
  src/components/media/MediaListContainer.tsx
  src/components/media/index.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordContents.tsx
  src/components/record/RecordListContainer.tsx
  src/components/record/RecordModalHeader.tsx
  src/components/record/index.tsx
  src/utils/constants/header.ts
  src/utils/mediaListData.ts
Labels: style

#149 fix: 기록관리 템플릿 수정 버그 해결
  src/components/Category/CategoryListContents.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/UpdateQuestion/UpdateQuestionOptionalContent.tsx
  src/components/UpdateTemplate/index.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
Labels: fix

#150 refactor: 관심사 별 provider 분리
  src/Router.tsx
  src/apis/record.ts
  src/components/Category/CategoryListContents.tsx
  src/components/Category/index.tsx
  src/components/Template/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateFooter.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/TemplateTitle.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/index.tsx
  src/components/common/DeleteModal.tsx
  src/components/common/Footer.tsx
  src/components/common/Modal.tsx
  src/components/common/QuestionBox.tsx
  src/components/common/SelectionBox.tsx
  src/components/media/MediaCategorySelector.tsx
  src/components/media/MediaListContainer.tsx
  src/components/media/index.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordContents.tsx
  src/components/record/index.tsx
  src/main.tsx
  src/pages/CategoryManagementPage.tsx
  src/pages/MediaManagementPage.tsx
  src/pages/RecordManagementPage.tsx
  src/store/CategoryProvider.tsx
  src/store/MediaProvider.tsx
  src/store/QuestionProvider.tsx
  src/store/RecordProvider.tsx
  src/store/SelectedIdProvider.tsx
  src/store/TemplateProvider.tsx
  src/store/index.tsx
  src/types/category.interface.ts
  src/types/recordDetail.interface.ts
  src/types/recordList.interface.ts
  src/types/template.interface.ts
  src/utils/recordData.ts
Labels: refactor

#151 docs: readme
  README.md
Labels: docs

#153 fix: 전체적인 버그 수정 #152
  src/apis/Category.ts
  src/apis/Login.ts
  src/components/Common/DeleteModal.tsx
  src/components/Common/EditBox.tsx
  src/components/Common/Footer.tsx
  src/components/Common/Header.tsx
  src/components/Common/Loading.tsx
  src/components/Common/Modal.tsx
  src/components/Common/QuestionBox.tsx
  src/components/Common/SelectionBox.tsx
  src/components/Login/LoginForm.tsx
  src/components/Media/MediaCard.tsx
  src/components/Media/MediaCategorySelector.tsx
  src/components/Media/MediaContent.tsx
  src/components/Media/MediaListContainer.tsx
  src/components/Media/index.tsx
  src/components/Record/RecordCard.tsx
  src/components/Record/RecordContents.tsx
  src/components/Record/RecordInfo.tsx
  src/components/Record/RecordListContainer.tsx
  src/components/Record/RecordModalHeader.tsx
  src/components/Record/RecordTypeSelector.tsx
  src/components/Record/index.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/index.tsx
  src/components/UpdateTemplate/index.tsx
Labels: fix, refactor
