Repository pie-sfac/5-17-smokedDuck, pull requests merged in 2023-07, with the labels that each got.

#6 feat: 라우팅 처리
  .eslintcache
  .gitignore
  src/App.tsx
  src/Router.tsx
  src/pages/LoginPage.tsx
  src/pages/NotFoundPage.tsx
Labels: feat

#7 feat: 공통 컴포넌트 개발 (모달)
  .eslintcache
  src/components/common/Modal.tsx
  src/pages/RecordManagementPage.tsx
Labels: feat

#16 chore: eslint rule 추가 및 절대 경로 설정
  .eslintrc.cjs
  src/App.tsx
  src/Router.tsx
  src/components/LoginForm.tsx
  src/components/common/Header.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/RecordManagementPage.tsx
  tsconfig.json
  vite.config.ts
Labels: chore

#20 feat: 기록관리 템플릿 리스트 화면 제작
  package-lock.json
  package.json
  src/App.tsx
  src/assets/hamburgerDots.svg
  src/components/common/DeleteModal.tsx
  src/components/common/EditBox.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordListContainer.tsx
  src/components/record/TypeSelector.tsx
  src/main.tsx
  src/pages/RecordManagementPage.tsx
  src/store/index.tsx
  src/utils/constants/recordList.ts
Labels: feat

#25 feat: footer 컴포넌트 제작
  src/App.tsx
  src/Router.tsx
  src/components/common/DeleteModal.tsx
  src/components/common/EditBox.tsx
  src/components/common/Footer.tsx
  src/components/record/RecordCard.tsx
  src/components/record/RecordListContainer.tsx
  src/pages/RecordManagementPage.tsx
  src/store/index.tsx
Labels: feat

#26 feat: 템플릿 생성 레이아웃 개발 (처치)
  src/assets/Condition.svg
  src/assets/EmptyQuestion.svg
  src/assets/Media.svg
  src/assets/Pain.svg
  src/assets/PainQuestion.svg
  src/assets/QuestionMark.svg
  src/assets/Selections.svg
  src/assets/Template.svg
  src/assets/Text.svg
  src/components/Question/QuestionContent.tsx
  src/components/Question/QuestionFooter.tsx
  src/components/Question/QuestionHeader.tsx
  src/components/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateFooter.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/Template/TemplateSelections.tsx
  src/components/Template/TemplateSubHeader.tsx
  src/components/Template/TemplateTitle.tsx
  src/components/Template/index.tsx
  src/components/common/Modal.tsx
  src/components/common/QuestionBox.tsx
  src/components/common/SelectionBox.tsx
  src/pages/MediaManagementPage.tsx
  src/pages/RecordManagementPage.tsx
  src/store/index.tsx
Labels: feat

#29 fix: 현재 페이지 헤더 표시
  src/components/common/Header.tsx
Labels: fix

#32 feat: 문항 추가 기능 개발 (처치)
  src/components/Question/QuestionContent.tsx
  src/components/Question/QuestionFooter.tsx
  src/components/Question/QuestionHeader.tsx
  src/components/Question/index.tsx
  src/components/Template/TemplateContent.tsx
  src/components/Template/TemplateFooter.tsx
  src/components/Template/TemplateQuestionSelections.tsx
  src/components/Template/TemplateSelectedQuestionContainer.tsx
  src/components/common/QuestionBox.tsx
  src/pages/RecordManagementPage.tsx
  src/store/index.tsx
  src/types/index.ts
  src/types/question.interface.ts
Labels: feat

#39 feat: 미디어 관리 화면에 생성된 링크 불러오기
  src/apis/Youtube.ts
  src/components/Link/LinkForm.tsx
  src/components/Link/LinkView.tsx
  src/components/Link/index.tsx
  src/components/media/MediaCard.tsx
  src/components/media/MediaContent.tsx
  src/components/media/MediaListContainer.tsx
  src/hooks/UseYoutubeVideo.tsx
  src/pages/MediaManagementPage.tsx
  src/store/index.tsx
  src/utils/constants/mediaList.ts
Labels: feat

#40 feat: 기본 문항 detail content 개발 (처치)
  src/components/Question/QuestionContent.tsx
Labels: feat

#41 feat: 클릭시 링크 정보 모달 띄우기
  src/components/Link/LinkView.tsx
  src/components/common/EditBox.tsx
  src/components/media/MediaCard.tsx
  src/components/media/MediaContent.tsx
  src/components/media/MediaListContainer.tsx
  src/hooks/UseYoutubeVideo.tsx
Labels: feat

#43 feat: 카테고리 삭제 기능 구현
  src/Router.tsx
  src/components/Category/CategoryDelete.tsx
  src/components/Category/CategorySelector.tsx
  src/components/Category/CategoryTab.tsx
  src/components/Category/index.tsx
  src/components/media/CategorySelector.tsx
  src/pages/CategoryManagementPage.tsx
  src/pages/MediaManagementPage.tsx
  src/store/index.tsx
  src/utils/constants/categoryList.ts
Labels: feat

#47 fix: 카테고리 eslint 수정
  src/components/Category/CategoryDelete.tsx
Labels: fix

#51 fix: 미디어 첨부 기능 수정
  src/components/Question/QuestionContent.tsx
  src/types/question.interface.ts
Labels: fix
